/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package desain;

import javax.swing.JOptionPane;

/**
 *
 * @author deazs
 */
public class Produk extends javax.swing.JPanel {
    private Barang brg;
    public Produk(String namaProduk,String kategori,String deskripsi,String foto,String toko,int harga,int stok) {
        initComponents();
        this.brg=new Barang(namaProduk,kategori,deskripsi,foto,toko,harga,stok);
        updateDisplay(this.brg);
    }
    public void updateDisplay(Barang brg){
        labelToko.setText(brg.getToko());
        labelNamaProduct.setText(brg.getNama());
        labelHarga.setText("Rp. "+String.valueOf(brg.getHarga()));
        labelStok.setText(String.valueOf(brg.getStok()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fPanelProduct2 = new desain.FPanelProduct();
        labelFoto = new javax.swing.JLabel();
        labelNamaProduct = new javax.swing.JLabel();
        labelToko = new javax.swing.JLabel();
        labelTulisanStok = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        labelStok = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        fPanelProduct2.setBackground(new java.awt.Color(255, 255, 255));
        fPanelProduct2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fPanelProduct2MouseClicked(evt);
            }
        });

        labelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/produk1.jpg"))); // NOI18N

        labelNamaProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNamaProduct.setText("Barang1");

        labelToko.setText("Udin");

        labelTulisanStok.setText("Stok :");

        labelHarga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelHarga.setText("Rp. 10.000,00");

        labelStok.setText("10");

        javax.swing.GroupLayout fPanelProduct2Layout = new javax.swing.GroupLayout(fPanelProduct2);
        fPanelProduct2.setLayout(fPanelProduct2Layout);
        fPanelProduct2Layout.setHorizontalGroup(
            fPanelProduct2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fPanelProduct2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fPanelProduct2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fPanelProduct2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(fPanelProduct2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNamaProduct)
                            .addGroup(fPanelProduct2Layout.createSequentialGroup()
                                .addComponent(labelTulisanStok)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelStok))
                            .addComponent(labelToko))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fPanelProduct2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelHarga)
                .addGap(15, 15, 15))
        );
        fPanelProduct2Layout.setVerticalGroup(
            fPanelProduct2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fPanelProduct2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNamaProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelToko)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fPanelProduct2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTulisanStok)
                    .addComponent(labelStok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelHarga)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fPanelProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fPanelProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fPanelProduct2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fPanelProduct2MouseClicked
        JOptionPane.showMessageDialog(null, "Anda Klik "+labelNamaProduct.getText());
    }//GEN-LAST:event_fPanelProduct2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private desain.FPanelProduct fPanelProduct2;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelNamaProduct;
    private javax.swing.JLabel labelStok;
    private javax.swing.JLabel labelToko;
    private javax.swing.JLabel labelTulisanStok;
    // End of variables declaration//GEN-END:variables
}
