/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desain;

import static desain.LogIn.filename;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author deazs
 */
public class RegisterSeller extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    Connection cn = koneksi.koneksiDatabase.BukaKoneksi();
    
    private String filename;
    /**
     * Creates new form RegisterSeller
     */
    public RegisterSeller() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        addPlaceholderStyle(txtEmail);
        addPlaceholderStyle(txtNo);
        addPlaceholderStyle(txtPassword);
        addPlaceholderStyle(txtRePassword);
        addPlaceholderStyle(txtNamaToko);
    }
    public void addPlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    public void removePlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.BLACK);
    }
    private void Bersih(){
        txtEmail.setText("");
        txtNo.setText("");
        txtPassword.setText("");
        txtRePassword.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRePassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        labelWarning = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelSignIn = new javax.swing.JLabel();
        labelAddPhoto = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNamaToko = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1110, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(1110, 900));

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/women2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel6)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel6)
                .addContainerGap(576, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tas2.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        jLabel3.setText("Register Seller");

        jLabel4.setText("Email");

        txtNo.setText("No HP");
        txtNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNoFocusLost(evt);
            }
        });

        jLabel5.setText("Re-Password");

        txtRePassword.setText("Re-Password");
        txtRePassword.setEchoChar('\u0000');
        txtRePassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRePasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRePasswordFocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("No HP");

        txtEmail.setText("Email");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        jLabel9.setText("Password");

        txtPassword.setText("Password");
        txtPassword.setEchoChar('\u0000');
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });

        labelWarning.setForeground(new java.awt.Color(255, 0, 51));

        jLabel7.setText("I have an account?");

        labelSignIn.setForeground(new java.awt.Color(255, 204, 102));
        labelSignIn.setText("LogIn");
        labelSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSignInMouseClicked(evt);
            }
        });

        labelAddPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAddPhoto.setText("<html>Ketuk Untuk <br/>Menambahkan foto</html>");
        labelAddPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelAddPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddPhotoMouseClicked(evt);
            }
        });

        jLabel10.setText("Nama Toko");

        txtNamaToko.setText("Nama Toko");
        txtNamaToko.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaTokoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNamaTokoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEmail)
                                .addComponent(txtNo)
                                .addComponent(jLabel9)
                                .addComponent(txtPassword)
                                .addComponent(txtRePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addComponent(txtNamaToko)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelWarning, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(99, 99, 99)
                        .addComponent(labelAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSignIn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(labelAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaToko, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(labelWarning)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelSignIn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1365, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoFocusGained
        if(txtNo.getText().equals("No HP")){
            txtNo.setText(null);
            txtNo.requestFocus();
            //remove placeholder
            removePlaceholderStyle(txtNo);
        }
    }//GEN-LAST:event_txtNoFocusGained

    private void txtNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoFocusLost
        if(txtNo.getText().length()==0){
            //add placeholder
            addPlaceholderStyle(txtNo);
            txtNo.setText("No HP");
        }
    }//GEN-LAST:event_txtNoFocusLost

    private void txtRePasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRePasswordFocusGained
        if(txtRePassword.getText().equals("Re-Password")){
            txtRePassword.setText(null);
            txtRePassword.requestFocus();
            //set Password Character
            txtRePassword.setEchoChar('\u2022');
            //remove placeholder
            removePlaceholderStyle(txtRePassword);
        }
    }//GEN-LAST:event_txtRePasswordFocusGained

    private void txtRePasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRePasswordFocusLost
        if(txtRePassword.getText().length()==0){
            //add placeholder
            addPlaceholderStyle(txtRePassword);
            txtRePassword.setText("Re-Password");
            txtRePassword.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_txtRePasswordFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {

            String newpath = "src////seller";
            File directory = new File(newpath);
            if (!directory.exists()){
                directory.mkdir();
            }
            File fileAwal = null;
            File fileAkhir = null;
            String ext = this.filename.substring(filename.lastIndexOf('.')+1);
            fileAwal = new File(filename);
            fileAkhir = new File(newpath+"////"+txtEmail.getText()+"."+ext);

            st = cn.createStatement();
            if (txtEmail.getText().equals("") || txtNo.getText().equals("") || txtPassword.getText().equals("") || txtRePassword.getText().equals("") || txtNamaToko.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong","Validasi Data",JOptionPane.ERROR_MESSAGE);
                return;
            }else{
                String cek="SELECT * FROM seller WHERE email = '" + txtEmail.getText()+"'";
                rs = st.executeQuery(cek);

                if (rs.next()){ //mengecek apabila emailnya sama
                    JOptionPane.showMessageDialog(null, "Maaf Email sudah digunakan");
                }else{
                    if (txtPassword.getText().equals(txtRePassword.getText())){
                        
                        String sql = "INSERT INTO seller VALUES ('"+txtEmail.getText()+
                        "','"+txtNo.getText()+
                        "','"+txtPassword.getText()+
                        "','"+0+
                        "','"+fileAkhir+
                        "','"+txtNamaToko.getText()+"')";
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                        Files.copy(fileAwal.toPath(), fileAkhir.toPath());

                        Bersih();

                        this.dispose();
                        LogInSeller lgS = new LogInSeller();
                        lgS.setVisible(true);
                        //                    lg.setLocationRelativeTo(null);
                    }else{
                        labelWarning.setText("Password tidak sama");
                        return;
                    }
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if(txtEmail.getText().equals("Email")){
            txtEmail.setText(null);
            txtEmail.requestFocus();
            //remove placeholder
            removePlaceholderStyle(txtEmail);
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(txtEmail.getText().length()==0){
            //add placeholder
            addPlaceholderStyle(txtEmail);
            txtEmail.setText("Email");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if(txtPassword.getText().equals("Password")){
            txtPassword.setText(null);
            txtPassword.requestFocus();
            //set Password Character
            txtPassword.setEchoChar('\u2022');
            //remove placeholder
            removePlaceholderStyle(txtPassword);
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if(txtPassword.getText().length()==0){
            //add placeholder
            addPlaceholderStyle(txtPassword);
            txtPassword.setText("Password");
            txtPassword.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void labelSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSignInMouseClicked
        this.dispose();
        LogInSeller lg = new LogInSeller();
        lg.setVisible(true);
    }//GEN-LAST:event_labelSignInMouseClicked

    private void labelAddPhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddPhotoMouseClicked
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.setFileFilter(new FileFilter() { // untuk memfiler type png dan jpg
                @Override
                public boolean accept(File file) {
                    String n = file.getName().toLowerCase();
                    if(file.isDirectory() || n.endsWith(".jpg") || n.endsWith(".png")){
                        return true;
                    }else{
                        return false;
                    }
                }

                @Override
                public String getDescription() {
                    return ".jpg | .png";
                }
            });
            int click = chooser.showOpenDialog(this);
            if (click == JFileChooser.APPROVE_OPTION){

                filename = chooser.getSelectedFile().getAbsolutePath();
                System.out.println(filename);
                labelAddPhoto.setText("");
                labelAddPhoto.setIcon(resizeImage(new ImageIcon(filename)));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_labelAddPhotoMouseClicked
    private ImageIcon resizeImage(ImageIcon img){
        return new ImageIcon(img.getImage().getScaledInstance(labelAddPhoto.getWidth()-2, labelAddPhoto.getHeight()-2,Image.SCALE_SMOOTH));
    }
    private void txtNamaTokoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaTokoFocusGained
        if(txtNamaToko.getText().equals("Nama Toko")){
            txtNamaToko.setText(null);
            txtNamaToko.requestFocus();
            //remove placeholder
            removePlaceholderStyle(txtNamaToko);
        }
    }//GEN-LAST:event_txtNamaTokoFocusGained

    private void txtNamaTokoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaTokoFocusLost
        if(txtNamaToko.getText().length()==0){
            //add placeholder
            addPlaceholderStyle(txtNamaToko);
            txtNamaToko.setText("Nama Toko");
        }
    }//GEN-LAST:event_txtNamaTokoFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterSeller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAddPhoto;
    private javax.swing.JLabel labelSignIn;
    private javax.swing.JLabel labelWarning;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNamaToko;
    private javax.swing.JTextField txtNo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    // End of variables declaration//GEN-END:variables
}
