/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desain;

import java.awt.Image;
import java.io.File;
import static java.lang.Math.random;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;


/**
 *
 * @author deazs
 */
public class UpdateProduct extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    Connection cn = koneksi.koneksiDatabase.BukaKoneksi();
    //ambil nama procut dari homePageSeller
    String namaProduct = HomePageSeller.namaProductToUpdate;
    //ambil nama toko dari Login
    String namaToko = LogInSeller.toko;
    
    String filename,pertama,kedua,ketiga,hasilFile;
    int idProduk;
    
    //cek apakah menambahkan foto baru
    boolean fotoSelected = false;
    
    
    

    /**
     * Creates new form UpdateProduct
     */
    public UpdateProduct() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        aksi();
    }
    public void aksi(){
        String harga,stok,kategori,deskripsi,fileName;
        
        try {
            st = cn.createStatement();
            String sql = "SELECT * FROM product WHERE toko = '"+namaToko+"' AND nama = '"+namaProduct+"'";
            rs = st.executeQuery(sql);
            if (rs.next()){
                harga = rs.getString("harga");
                stok = rs.getString("stok");
                kategori = rs.getString("kategori");
                deskripsi = rs.getString("deskripsi");
                fileName = rs.getString("foto");
                idProduk = rs.getInt("id");
                
                pertama = fileName.substring(0,3);
                kedua = fileName.substring(3,9);
                ketiga = fileName.substring(9);
                hasilFile = pertama+"\\"+kedua+"\\"+ketiga; 
                
                txtNamaProduct.setText(namaProduct);
                txtHarga.setText(harga);
                txtStok.setText(stok);
                txtKategori.setText(kategori);
                txtDeskripsi.setText(deskripsi);
                
                File f = new File(hasilFile);
                ImageIcon icon = new ImageIcon(f.toString());
                Image img = icon.getImage().getScaledInstance(labelFoto.getWidth(), labelFoto.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon ic = new ImageIcon(img);
                labelFoto.setIcon(ic);
            }
        } catch (Exception e) {
        }
    }
    class product extends TambahProduct{
        String nama="",kategori="",deskripsi="",foto="",toko="";
        String harga,stok;
        public product(){
            nama = txtNamaProduct.getText();
            kategori = txtKategori.getText();
            deskripsi = txtDeskripsi.getText();
            harga = txtHarga.getText();
            stok = txtStok.getText();
            toko = namaToko;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fPanel5 = new desain.FPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNamaProduct = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKategori = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        labelFoto = new javax.swing.JLabel();
        fPanel1 = new desain.FPanel();
        labelKonfirmasi = new javax.swing.JLabel();
        txtDeskripsi = new desain.FtxtField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1110, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(1110, 900));

        jPanel3.setBackground(new java.awt.Color(251, 206, 49));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("WarungPedia");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        fPanel5.setBackground(new java.awt.Color(251, 206, 49));
        fPanel5.setRoundBottomLeft(10);
        fPanel5.setRoundBottomRight(10);
        fPanel5.setRoundTopLeft(10);
        fPanel5.setRoundTopRight(10);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Konfigurasi Produk");

        javax.swing.GroupLayout fPanel5Layout = new javax.swing.GroupLayout(fPanel5);
        fPanel5.setLayout(fPanel5Layout);
        fPanel5Layout.setHorizontalGroup(
            fPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );
        fPanel5Layout.setVerticalGroup(
            fPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        txtNamaProduct.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtNamaProduct.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtHarga.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtStok.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Rp.");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Stok : ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Kategori : ");

        txtKategori.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Deskripsi");

        labelFoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFoto.setText("Klik Untuk Menambahkan Foto");
        labelFoto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        labelFoto.setPreferredSize(new java.awt.Dimension(186, 124));
        labelFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFotoMouseClicked(evt);
            }
        });

        fPanel1.setBackground(new java.awt.Color(251, 206, 49));
        fPanel1.setRoundBottomLeft(10);
        fPanel1.setRoundBottomRight(10);
        fPanel1.setRoundTopLeft(10);
        fPanel1.setRoundTopRight(10);

        labelKonfirmasi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelKonfirmasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKonfirmasi.setText("Konfirmasi");
        labelKonfirmasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKonfirmasiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fPanel1Layout = new javax.swing.GroupLayout(fPanel1);
        fPanel1.setLayout(fPanel1Layout);
        fPanel1Layout.setHorizontalGroup(
            fPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelKonfirmasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        fPanel1Layout.setVerticalGroup(
            fPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelKonfirmasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        txtDeskripsi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDeskripsi.setText("Masukkan deskripsi produk");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(195, 195, 195)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNamaProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(883, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(txtNamaProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(654, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFotoMouseClicked
        product p = new product();
        if (p.nama.equals("") ||  p.kategori.equals("") || p.deskripsi.equals("") || p.harga.equals("") || p.stok.equals("") || p.toko .equals("")){
            JOptionPane.showMessageDialog(null, "Harap isi semua sebelum menambahkan foto");
        }else{

            try {
                JFileChooser chooser = new JFileChooser();
                chooser.setFileFilter(new FileFilter() { // untuk memfiler type png dan jpg
                    @Override
                    public boolean accept(File file) {
                        String n = file.getName().toLowerCase();
                        if(file.isDirectory() || n.endsWith(".jpg") || n.endsWith(".png")){
                            return true;
                        }else{
                            return false;
                        }
                    }

                    @Override
                    public String getDescription() {
                        return ".jpg | .png";
                    }
                });
                int click = chooser.showOpenDialog(this);
                if (click == JFileChooser.APPROVE_OPTION){

                    filename = chooser.getSelectedFile().getAbsolutePath();
                    labelFoto.setText("");
                    labelFoto.setIcon(resizeImage(new ImageIcon(filename)));
                    fotoSelected = true;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_labelFotoMouseClicked
    private ImageIcon resizeImage(ImageIcon img){
        return new ImageIcon(img.getImage().getScaledInstance(labelFoto.getWidth()-2, labelFoto.getHeight()-2,Image.SCALE_SMOOTH));
    }
    private void labelKonfirmasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKonfirmasiMouseClicked
        try {
            if (fotoSelected){
                
                Random random = new Random();
                int randomNumber = random.nextInt(100) + 1;
                
                String newpath = "src////produk";
                File directory = new File(newpath);
                if (!directory.exists()){
                    directory.mkdir();
                }
                File fileAwal = null;
                File fileAkhir = null;
                String ext = this.filename.substring(filename.lastIndexOf('.')+1);
                fileAwal = new File(filename);
                fileAkhir = new File(newpath+"////"+txtNamaProduct.getText()+randomNumber+"."+ext);
                System.out.println(fileAkhir);

                product p = new product();
                int harga = Integer.parseInt(p.harga);
                int stok = Integer.parseInt(p.stok);
                st = cn.createStatement();
                if (p.nama.equals("") || p.harga.equals("") || p.stok.equals("") || p.kategori.equals("") ||
                    p.deskripsi.equals("") || fileAkhir.equals("")){
                    JOptionPane.showMessageDialog(null, "Data tidak boleh kosong","Validasi Data",JOptionPane.ERROR_MESSAGE);
                }else{
                    String sql = "UPDATE product SET " +
                        "nama = '" + p.nama + "', " +
                        "harga = '" + harga + "', " +
                        "stok = '" + stok + "', " +
                        "kategori = '" + p.kategori + "', " +
                        "deskripsi = '" + p.deskripsi + "', " +
                        "foto = '" + fileAkhir + "', " +
                        "toko = '" + p.toko + "' " +
                        "WHERE id = " + idProduk;
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"Produk berhasil diupdate");
                    Files.copy(fileAwal.toPath(), fileAkhir.toPath());

                    this.dispose();
                    HomePageSeller hp = new HomePageSeller();
                    hp.setVisible(true);
                }
            }else{
                product p = new product();
                int harga = Integer.parseInt(p.harga);
                int stok = Integer.parseInt(p.stok);
                st = cn.createStatement();
                if (p.nama.equals("") || p.harga.equals("") || p.stok.equals("") || p.kategori.equals("") ||
                    p.deskripsi.equals("")){
                    JOptionPane.showMessageDialog(null, "Data tidak boleh kosong","Validasi Data",JOptionPane.ERROR_MESSAGE);
                }else{
                    String sql = "UPDATE product SET " +
                        "nama = '" + p.nama + "', " +
                        "harga = '" + harga + "', " +
                        "stok = '" + stok + "', " +
                        "kategori = '" + p.kategori + "', " +
                        "deskripsi = '" + p.deskripsi + "', " +
                        "toko = '" + p.toko + "' " +
                        "WHERE id = " + idProduk;
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"Produk berhasil diupdate");

                    this.dispose();
                    HomePageSeller hp = new HomePageSeller();
                    hp.setVisible(true);
                }
            }
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_labelKonfirmasiMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private desain.FPanel fPanel1;
    private desain.FPanel fPanel5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelKonfirmasi;
    private desain.FtxtField txtDeskripsi;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKategori;
    private javax.swing.JTextField txtNamaProduct;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
